name: performance-benchmarking
channels:
  - conda-forge
dependencies:
  - pytest
  - pytest-benchmark
  - python=3.11
  - pip
  - pip:
    - hatch
    - asv
    - itkwasm-mesh-io
    - itkwasm-image-io
